/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/menu.ts" />
///<reference path="../scenes/angrymom.ts"/>
///<reference path="../scenes/tame.ts"/>
///<reference path="../scenes/hero.ts"/>
/// <reference path="../scenes/soldier.ts" />
/// <reference path="../scenes/hopeless.ts" />
/// <reference path="../scenes/death.ts" />
/// <reference path="../scenes/game.ts" />
//# sourceMappingURL=_reference.js.map